name: Trigger Jitpack Build
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Jitpack Build
        run: curl "https://jitpack.io/com/github/kodingdevelopment/catalyst/${GITHUB_SHA:0:10}/build.log"